# https://github.com/vitejs/vite/discussions/19168
server {
  listen 80;
  server_name acme.com;

  location = /sw.js {
      alias /var/www/out/sw.js;
      default_type application/javascript;
      add_header Cache-Control "no-store, no-cache, must-revalidate" always;
      etag off;
  }
 
  location / {
      alias /var/www/out/;
      index index.html;
      try_files $uri $uri/ /index.html;
  }
}
