# https://github.com/vitejs/vite/discussions/19168
server {
  listen 80;
  server_name acme.com;
  root /var/www/out;

  location = /app {
      return 308 /app/;
  }

  location = /app/sw.js {
      try_files $uri =404;
      default_type application/javascript;
      add_header Cache-Control "no-store, no-cache, must-revalidate" always;
      etag off;
  }

  location /app/ {
      try_files $uri $uri/ /app/index.html;
  }

  location / {
      try_files $uri $uri/ /index.html;
  }
}
